# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
      - dependencies
      - Area-Build & Infrastructure
      - External
  categories:
    - title: Breaking Changes 🧨
      labels:
        - breaking change
    - title: Exciting New Features 🎉
      labels:
        - enhancement
        - new feature
    - title: Bug fixes🛠️
      labels:
        - bug
    - title: Accessibility
      labels:
        - Area-Accessibility
    - title: Automation
      labels:
        - Area-Automation
    - title: Auth
      labels:
        - Area-Auth
    - title: API
      labels:
        - Area-API
    - title: C#
      labels:
        - Area-C#
    - title: Documentation
      labels:
        - Area-Documentation
    - title: F#
      labels:
        - Area-F#
    - title: Formatting
      labels:
        - Area-Formatting
    - title: HttpKernel, Visual Studio HTTP Editor
      labels:
        - Area-HTTP
    - title: JavaScript HTML CSS
      labels:
        - Area-JavaScript HTML CSS
    - title: Jupyter
      labels:
        - Area-Jupyter
    - title: Jupyter subkernels (Python, R, Julia, etc.)
      labels:
        - Area-Jupyter subkernels
    - title: Language Services
      labels:
        - Area-Language Services
    - title: Localization and Globalization
      labels:
        - Area-Localization and Globalization
    - title: Messaging, Comms, and Scheduling
      labels:
        - Area-Messaging / scheduling / comms
    - title: Packages and Extensions
      labels:
        - Area-Packages and Extensions
    - title: Performance
      labels:
        - Area-Performance
    - title: Polyglot Notebooks Extension
      labels:
        - Area-Polyglot Notebooks Extension
    - title: PowerShell
      labels:
        - Area-PowerShell
    - title: Python
      labels:
        - Area-Python
    - title: SQL, KQL, and data querying
      labels:
        - Area-SQL / data querying
    - title: Magic Commands & Submission Parsing
      labels:
        - Area-Submission Parsing & Magic Commands
    - title: Try .NET
      labels:
        - Area-Try .NET
    - title: Variable sharing
      labels:
        - Area-Variable sharing
    - title: Visualization
      labels:
        - Area-Visualization

