# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
      - dependencies
      - Area-Build & Infrastructure
  categories:
    - title: Breaking Changes 🧨
      labels:
        - "breaking change"
    - title: Exciting New Features 🎉
      labels:
        - enhancement
    - title: Bug fixes🛠️
      labels:
        - bug
    - title: Area-Automation 
      labels:
        - Area-Automation
    - title: "Area-Azure Data Studio"
      labels:
        - "Area-Azure Data Studio"
    - title: Area-C#
      labels:
        - Area-C#
    - title: Area-Documentation
      labels:
        - Area-Documentation
    - title: Area-F#
      labels:
        - Area-F#
    - title: Area-Formatting
      labels:
        - Area-Formatting
   - title: Area-JavaScript HTML CSS
      labels:
        - "Area-JavaScript HTML CSS"
   - title: Area-Jupyter
      labels:
        - "Area-Jupyter"
   - title: Area-Language Services
      labels:
        - "Area-Language Services"
   - title: Area-Messaging and Comms
      labels:
        - "Area-Messaging and Comms"
   - title: Area-Packages and Extensions
      labels:
        - "Area-Packages and Extensions"
   - title: Area-Performance
      labels:
        - "Area-Performance"
   - title: Area-PowerShell
      labels:
        - "Area-PowerShell"
   - title: Area-Python
      labels:
        - "Area-Python"
   - title: Area-SQL / data querying
      labels:
        - "Area-SQL / data querying"
   - title: Area-Variable sharing
      labels:
        - "Area-Variable sharing"
   - title: Area-Visualization
      labels:
        - "Area-Visualization"
   - title: Area-VisualStudio
      labels:
        - "Area-VisualStudio"
   - title: Area-VS Code Extension
      labels:
        - "Area-VS Code Extension"
   - title: Area-VS Code Jupyter Extension Interop
      labels:
        - "Area-VS Code Jupyter Extension Interop"
   - title: Area-WebAssembly
      labels:
        - "Area-WebAssembly"
    - title: Other Changes
      labels:
        - "*"
