//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.DotNet.Interactive.App {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.DotNet.Interactive.App.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactive programming for .NET..
        /// </summary>
        internal static string Cli_dotnet_interactive_Description {
            get {
                return ResourceManager.GetString("Cli_dotnet_interactive_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to a connection file provided by Jupyter.
        /// </summary>
        internal static string Cli_dotnet_interactive_jupyter_connection_file_Description {
            get {
                return ResourceManager.GetString("Cli_dotnet_interactive_jupyter_connection_file_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default language for the kernel.
        /// </summary>
        internal static string Cli_dotnet_interactive_jupyter_default_kernel_Description {
            get {
                return ResourceManager.GetString("Cli_dotnet_interactive_jupyter_default_kernel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts dotnet-interactive as a Jupyter kernel.
        /// </summary>
        internal static string Cli_dotnet_interactive_jupyter_Description {
            get {
                return ResourceManager.GetString("Cli_dotnet_interactive_jupyter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install the .NET kernel for Jupyter.
        /// </summary>
        internal static string Cli_dotnet_interactive_jupyter_install_Description {
            get {
                return ResourceManager.GetString("Cli_dotnet_interactive_jupyter_install_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the range of ports to use to enable HTTP services.
        /// </summary>
        internal static string Cli_dotnet_interactive_jupyter_install_http_port_range_Description {
            get {
                return ResourceManager.GetString("Cli_dotnet_interactive_jupyter_install_http_port_range_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installs the kernel specs to the specified directory.
        /// </summary>
        internal static string Cli_dotnet_interactive_jupyter_install_path_Description {
            get {
                return ResourceManager.GetString("Cli_dotnet_interactive_jupyter_install_path_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable file logging to the specified directory.
        /// </summary>
        internal static string Cli_dotnet_interactive_log_path_Description {
            get {
                return ResourceManager.GetString("Cli_dotnet_interactive_log_path_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts a process to parse and serialize notebooks..
        /// </summary>
        internal static string Cli_dotnet_interactive_notebook_parser_Description {
            get {
                return ResourceManager.GetString("Cli_dotnet_interactive_notebook_parser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts dotnet-interactive with kernel functionality exposed over standard I/O.
        /// </summary>
        internal static string Cli_dotnet_interactive_stdio_Description {
            get {
                return ResourceManager.GetString("Cli_dotnet_interactive_stdio_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the port on which to enable HTTP services.
        /// </summary>
        internal static string Cli_dotnet_interactive_stdio_http_port_Description {
            get {
                return ResourceManager.GetString("Cli_dotnet_interactive_stdio_http_port_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot specify both {0} and {1} together.
        /// </summary>
        internal static string Cli_dotnet_interactive_stdio_http_port_ErrorMessageCannotSpecifyBoth {
            get {
                return ResourceManager.GetString("Cli_dotnet_interactive_stdio_http_port_ErrorMessageCannotSpecifyBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify a port number or *..
        /// </summary>
        internal static string Cli_dotnet_interactive_stdio_http_port_ErrorMessageMustSpecifyPortNumber {
            get {
                return ResourceManager.GetString("Cli_dotnet_interactive_stdio_http_port_ErrorMessageMustSpecifyPortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the range of ports to use to enable HTTP services.
        /// </summary>
        internal static string Cli_dotnet_interactive_stdio_http_port_range_Description {
            get {
                return ResourceManager.GetString("Cli_dotnet_interactive_stdio_http_port_range_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the kernel host..
        /// </summary>
        internal static string Cli_dotnet_interactive_stdio_kernel_host_Description {
            get {
                return ResourceManager.GetString("Cli_dotnet_interactive_stdio_kernel_host_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable preview kernel features..
        /// </summary>
        internal static string Cli_dotnet_interactive_stdio_preview_Description {
            get {
                return ResourceManager.GetString("Cli_dotnet_interactive_stdio_preview_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working directory to which to change after launching the kernel..
        /// </summary>
        internal static string Cli_dotnet_interactive_stdio_working_directory_Description {
            get {
                return ResourceManager.GetString("Cli_dotnet_interactive_stdio_working_directory_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable verbose logging to the console.
        /// </summary>
        internal static string Cli_dotnet_interactive_verbose_Description {
            get {
                return ResourceManager.GetString("Cli_dotnet_interactive_verbose_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify a port range as StartPort-EndPort.
        /// </summary>
        internal static string Cli_ErrorMessage_MustSpecifyPortRangeAsStartPortEndPort {
            get {
                return ResourceManager.GetString("Cli_ErrorMessage_MustSpecifyPortRangeAsStartPortEndPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start port must be lower then end port.
        /// </summary>
        internal static string Cli_ErrorMessage_StartPortMustBeLower {
            get {
                return ResourceManager.GetString("Cli_ErrorMessage_StartPortMustBeLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify a port range.
        /// </summary>
        internal static string Cli_ErrorMessageMustSpecifyPortRange {
            get {
                return ResourceManager.GetString("Cli_ErrorMessageMustSpecifyPortRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show version and build information.
        /// </summary>
        internal static string Magics_about_Description {
            get {
                return ResourceManager.GetString("Magics_about_Description", resourceCulture);
            }
        }
    }
}
