//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.DotNet.Interactive.App {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.DotNet.Interactive.App.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to constructing webhost.
        /// </summary>
        internal static string ConstructingWebhostInfo {
            get {
                return ResourceManager.GetString("ConstructingWebhostInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default language for the kernel.
        /// </summary>
        internal static string DefaultKernelOptionDescription {
            get {
                return ResourceManager.GetString("DefaultKernelOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactive programming for .NET..
        /// </summary>
        internal static string DotnetInteractiveCommandDescription {
            get {
                return ResourceManager.GetString("DotnetInteractiveCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to a connection file provided by Jupyter.
        /// </summary>
        internal static string JupyterConnectionFileOptionDescription {
            get {
                return ResourceManager.GetString("JupyterConnectionFileOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the range of ports to use to enable HTTP services.
        /// </summary>
        internal static string JupyterHttpPortRangeOptionDescription {
            get {
                return ResourceManager.GetString("JupyterHttpPortRangeOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install the .NET kernel for Jupyter.
        /// </summary>
        internal static string JupyterInstallDescription {
            get {
                return ResourceManager.GetString("JupyterInstallDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts dotnet-interactive as a Jupyter kernel.
        /// </summary>
        internal static string JupyterStartsDescription {
            get {
                return ResourceManager.GetString("JupyterStartsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable file logging to the specified directory.
        /// </summary>
        internal static string LogPathOptionDescription {
            get {
                return ResourceManager.GetString("LogPathOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts a process to parse and serialize notebooks..
        /// </summary>
        internal static string NotebookParserCommandDescription {
            get {
                return ResourceManager.GetString("NotebookParserCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify a port range.
        /// </summary>
        internal static string NotebookParserErrorMessageMustSpecifyPortRange {
            get {
                return ResourceManager.GetString("NotebookParserErrorMessageMustSpecifyPortRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify a port range as StartPort-EndPort.
        /// </summary>
        internal static string NotebookParserErrorMessageMustSpecifyPortRangeAsStartPortEndPort {
            get {
                return ResourceManager.GetString("NotebookParserErrorMessageMustSpecifyPortRangeAsStartPortEndPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start port must be lower then end port.
        /// </summary>
        internal static string NotebookParserErrorMessageStartPortMustBelower {
            get {
                return ResourceManager.GetString("NotebookParserErrorMessageStartPortMustBelower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installs the kernel specs to the specified directory.
        /// </summary>
        internal static string PathOptionsDescription {
            get {
                return ResourceManager.GetString("PathOptionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starting  kestrel server.
        /// </summary>
        internal static string StartingKestrelServerInfo {
            get {
                return ResourceManager.GetString("StartingKestrelServerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts dotnet-interactive with kernel functionality exposed over standard I/O.
        /// </summary>
        internal static string StdIoCommandDescription {
            get {
                return ResourceManager.GetString("StdIoCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot specify both {0} and {1} together.
        /// </summary>
        internal static string StdIoErrorMessageCannotSpecifyBoth {
            get {
                return ResourceManager.GetString("StdIoErrorMessageCannotSpecifyBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify a port number or *..
        /// </summary>
        internal static string StdIoErrorMessageMustSpecifyPortNumber {
            get {
                return ResourceManager.GetString("StdIoErrorMessageMustSpecifyPortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the port on which to enable HTTP services.
        /// </summary>
        internal static string StdIoHttpPortOptionDescription {
            get {
                return ResourceManager.GetString("StdIoHttpPortOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the range of ports to use to enable HTTP services.
        /// </summary>
        internal static string StdIoHttpPortRangeOptionDescription {
            get {
                return ResourceManager.GetString("StdIoHttpPortRangeOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the kernel host..
        /// </summary>
        internal static string StdIoKernelHostOptionDescription {
            get {
                return ResourceManager.GetString("StdIoKernelHostOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable preview kernel features..
        /// </summary>
        internal static string StdIoPreviewOptionDescription {
            get {
                return ResourceManager.GetString("StdIoPreviewOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working directory to which to change after launching the kernel..
        /// </summary>
        internal static string StdIoWorkingDirectoryOptionDescription {
            get {
                return ResourceManager.GetString("StdIoWorkingDirectoryOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable verbose logging to the console.
        /// </summary>
        internal static string VerboseOptionDescription {
            get {
                return ResourceManager.GetString("VerboseOptionDescription", resourceCulture);
            }
        }
    }
}
